### ISSUE TITLE
Mechanics Development Plan

### ISSUE THREAD

**Issue by tjstienstra** [mechmotum/sympy#1]
This issue keeps track of the progress of the new mechanics structure for `sympy.physics.mechanics`. Feel free to leave any comments and ask clarification on a point. The list will be updated with references to the PRs once they exist.

- [ ] Update the bodies structure: `_Body`, `Particle(_Body)`, `RigidBody(_Body)` (PR: #2)
- [ ] Implement compatibility of `Particle` and `RigidBody` with `Joint`
- [ ] Deprecate `Body`
- [ ] Implement `InertiaTuple`
- [ ] Implement loads: `_Load`, `Force(_Load)`, `Torque(_Load)`
- [ ] Implement `System` and deprecate `JointsMethod`
- [ ] Update `_Method`
- [ ] Enhance bodies functionality:
  - [ ] Implement `RigidBody.as_thin_rod`
  - [ ] Implement `_Body.add_point` and `_Body.get_point`
- [ ] Implement static generalized coordinates in `Joint`, e.g. parse `pi / 2` as generalized coordinate to a joint
- [ ] Implement efficient kdes choice in the joints framework
- [ ] Implement `CustomJoint`

**Comment by brocksam** [comment]
Related worked involves adding support on top of `sympy.physics.mechanics` for biomechanical modelling. I propose that we initially add this in `sympy.physics._biomechanics` during development and ensure that it isn't released as part of SymPy until it's been battle tested. This should help ensure that a solid and future-proofed API is developed.

A similar tracker for `sympy.physics._biomechanics` tasks is listed below and should also be updated with references to PRs once they exist.

- [ ] Create benchmarks scripts:
  - [ ] [Tug of war model](https://github.com/opensim-org/opensim-models/tree/master/Models/Tug_of_War)
  - [ ] [Simple arm model](https://www.sciencedirect.com/science/article/abs/pii/002192909390608H)
  - [ ] [Squat-to-stand model](https://github.com/opensim-org/opensim-moco/blob/master/Moco/Bindings/Java/Matlab/Examples/exampleSquatToStand/squatToStand_3dof9musc.osim)
  - [ ] [2D pedalling cyclist](https://www.sciencedirect.com/science/article/abs/pii/002192909390608H)
  - [ ] [3D pedalling cyclist](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0264346)
  - [ ] 3D steering cyclist
- [ ] Implement `Actuator`
- [ ] Implement `Musculotendon` with force-length and force-velocity curves based on [Millard et al. (2013)](https://asmedigitalcollection.asme.org/biomechanical/article-abstract/135/2/021005/371394/Flexing-Computational-Muscle-Modeling-and?redirectedFrom=fulltext) and [De Groote et al. (2016)](https://link.springer.com/article/10.1007/s10439-016-1591-9), and activation dynamics based on [De Groote et al. (2016)](https://link.springer.com/article/10.1007/s10439-016-1591-9)
- [ ] Implement musculotendon pathways: `ViaPoint`, `WrappingSurface`

**Comment by moorepants** [comment]
Are you mistakenly opening up issues/PRs on this fork of sympy? (mechmotum/sympy)?
